config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :schools do
    resources :teachers
  end

  resources :teachers do
    resources :ratings
  end

  root 'welcome#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :user
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :teachers, dependent: :destroy
  validates :name, presence: true,
                   length: { minimum: 5 }
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  has_many :ratings, dependent: :destroy
  has_many :users

  def name
    "#{firstName} #{middleName} #{lastName}"
  end

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ratings
  has_many :teachers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_teacher

  def new
    get_teacher
    @rating = current_user.ratings.build
  end

  def create
    get_teacher
    @rating = current_user.ratings.create(rating_params)
    if @rating.save
      redirect_to school_teacher_path(@teacher.school, @teacher)
    else
      render 'new'
    end
  end

  def destroy
    get_teacher
    @rating = @teacher.ratings.find(params[:id])
    @rating.destroy

    redirect_to school_teacher_path(@teacher.school, @teacher)
  end

  def get_teacher
    @teacher = Teacher.find(params[:teacher_id])
  end

  private

    def rating_params
      params.require(:rating).permit(:easiness, :helpfulness, :clarity, :comment,
      :teacher_id, :school_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def show
    @school = School.find(params[:id])
  end

  def new
    @school = School.new
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])

    if @school.update(school_params)
      redirect_to schools_path
    else
      render 'edit'
    end
  end

  def index
    @schools = School.all
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to schools_path
    else
      render 'new'
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to schools_path
  end

  private

    def school_params
      params.require(:school).permit(:name)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    get_school
    @teacher = @school.teachers.build
  end

  def show
    get_school
    @teacher = Teacher.find(params[:id])
  end

  def edit
    get_school
    @teacher = Teacher.find(params[:id])
  end

  def update
    get_school
    @teacher = Teacher.find(params[:id])

    if @teacher.update(teacher_params)
      redirect_to school_path(params[:school_id])
    else
      render 'edit'
    end
  end

  def destroy
    get_school
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    redirect_to school_path(params[:school_id])
  end

  def create
    get_school
    @teacher = @school.teachers.build(teacher_params)
    if @teacher.save
      redirect_to school_path(params[:school_id])
    else
      render 'new'
    end
  end

  def get_school
   @school = School.find(params[:school_id])
  end

  private

    def teacher_params
      params.require(:teacher).permit(:firstName, :lastName, :middleName, :school_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratemyprofessor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile',            edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

  <%= yield %>
</body>
</html>

app/views/ratings/new.html.erb
<h1>Teacher Rating</h1>
<%= form_for([@teacher, @rating]) do |f| %>
  <p>
    <%= f.label :clarity %>
    <%= f.text_field :clarity %>
  </p>

  <p>
    <%= f.label :easiness %>
    <%= f.text_field :easiness %>
  </p>

  <p>
    <%= f.label :helpfulness %>
    <%= f.text_field :helpfulness %>
  </p>

  <p>
    <%= f.label :comment %>
    <br>
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/schools/_form.html.erb
<%= form_for :school, url: schools_path do |f| %>

  <!-- tell the user that something went wrong -->
  <% if @school.errors.any? %>
    <div class="" id="error_explaination">
      <h2>
        <%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:
      </h2>
      <ul>
        <% @school.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/schools/edit.html.erb
<h1>Edit School</h1>

<%= form_for :school, url: school_path(@school), method: :patch do |f| %>

<!-- tell the user that something went wrong -->
<% if @school.errors.any? %>
  <div class="" id="error_explaination">
    <h2>
      <%= pluralize(@school.errors.count, "error") %> prohibited this school from being edited:
    </h2>
    <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/schools/index.html.erb
<% @schools.each do |school| %>
  <%= school.name %>

  <!-- Remember to pass the school object or school id to school_path method. Otherwise, it won't work! -->
  <%= link_to "Info", school_path(school), class: "btn btn-info" %>
  |
  <%= link_to "edit", edit_school_path(school), class: "btn btn-primary" %>
  |
  <%= link_to "Destroy", school_path(school), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
<br>
<% end %>

<p>
  <%= link_to "Create new school", new_school_path, class: "btn btn-primary" %>
</p>

<p>
  <%= link_to "Home", root_path, class: "btn btn-primary" %>
</p>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to "Home", root_path, class: "btn btn-primary" %>

app/views/schools/show.html.erb
<h1>School Information</h1>
<p>
  <%= @school.name %>
</p>

<h2>List of Teachers</h2>

<%= @school.teachers.each do |teacher| %>
  <%= teacher.to_s %>
  <%= link_to "Info", school_teacher_path(@school, teacher), class: "btn btn-info" %>
  <%= link_to 'Destroy', school_teacher_path(@school, teacher),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
  |
  <%= link_to "Edit", edit_school_teacher_path(@school, teacher), class: "btn btn-primary" %>
  <br>
<% end %>

<p>
  <%= link_to "Create new teacher", new_school_teacher_path(@school), class: "btn btn-primary" %>
</p>

<p>
  <%= link_to "Back to School List", schools_path, class: "btn btn-primary" %>
</p>

app/views/teachers/_form.html.erb
<%= form_for([@school, @teacher]) do |f| %>
  <p>
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </p>

  <p>
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </p>

  <p>
    <%= f.label :middleName %><br>
    <%= f.text_field :middleName %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/teachers/edit.html.erb
<%= render 'form' %>

app/views/teachers/new.html.erb
<%= render 'form' %>

app/views/teachers/show.html.erb
<!-- Caculate the average rating of the teacher -->
<h1>Average ratings:</h1>
<p>Clarity:
  <%= @teacher.ratings.average(:clarity) %>
</p>
<p>Easiness:
  <%= @teacher.ratings.average(:easiness) %>
</p>
<p>Helpfulness:
  <%= @teacher.ratings.average(:helpfulness) %>
</p>
<hr>

<!-- Show all the ratings -->
<h2>All the ratings:</h2>
<div>
  <%= @teacher.ratings.each do |rating| %>

    <p>Clarity:
      <%= rating.clarity %>
    </p>

    <p>Helpfulness:
      <%= rating.helpfulness %>
    </p>

    <p>Easiness:
      <%= rating.easiness %>
    </p>

    <p>Comment:
      <%= rating.comment %>
    </p>

    <%= link_to "Delete rating", [rating.teacher, rating], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>

    <hr>
  <% end %>
</div>

<p>
  <%= link_to "Rate teacher", new_teacher_rating_path(@teacher), class: "btn btn-primary" %>
</p>

<p>
  <%= link_to "Back to school", school_path(@school), class: "btn btn-primary" %>
</p>

app/views/welcome/index.html.erb
<%= render 'navbar' %>
<h1>List of schools</h1>
<p>
  <%= link_to "Create new school", new_school_path, class: "btn btn-primary" %>
</p>

<p>
  <%= link_to "Show all schools", schools_path, class: "btn btn-primary" %>
</p>